version: '3.1'

services:

  app:
    build: .
    environment:
      DB_URI: "db:mysql://root:awesomepassword@db:3306/ghost"
      SERVICE_NAME: "Custom service"
      ADMIN_API_ID: "5d1e94e87708cd00017fee06"
      ADMIN_SECRET: "ec334cba073c3a1f0e2689ca5063beeee1bab3bded2901878edf4a43ffc5ff9d"
      CONTENT_SECRET: "08d0c8c76380072ed33e6b0109"
      LOGIN_EMAIL: "test01@mail.com"
      # password = long_pass_01
      LOGIN_PASSWORD: '$$2a$$10$$FV87Su881bCz.GPWVYni5.HXqca5A9LHp3qLnKA3Mg.mkjs2NNCyi'
    working_dir: /app
    volumes:
      - .:/app

  ghost:
    image: ghost:latest
    restart: always
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: awesomepassword
      database__connection__database: ghost
    ports:
      - 8080:2368
    volumes:
      - ./src/content:/var/lib/ghost/content
      - ./src/config.development.json:/var/lib/ghost/config.development.json
      - ./src/config.production.json:/var/lib/ghost/config.production.json
      - ./data/assets:/var/lib/ghost/content/images

  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: awesomepassword
